### ISSUE TITLE
Executable is missing

### ISSUE THREAD

**Issue by svdb** [4np/BeleefDeLente#1]
You don't expect my wife and I to install Swift and and figure out how to compile this project... ;)

**Comment by 4np** [comment]
No, definitely not :+1: You can download [the latest release of the screensaver here](https://github.com/4np/BeleefDeLente/releases/latest) (get the `BeleefDeLente.saver.zip`, extract the zipfile and doubleclick on the `BeleefDeLente.saver` to install). I improved the `README.md` and the release notes to make the installation process a bit more clear...
